Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -14,6 +14,11 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: make philosophers
-        run: make if [ $? -ne 0 ]; then echo "::error::Command failed - ❌"; fi
+        run: |
+          make
+          if [ $? -ne 0 ]
+          then
+            echo "::error::Command failed - ❌"
+          fi
       - name: success
         run: echo "Success"
